### ISSUE TITLE
Create our facebook app

### ISSUE THREAD

**Issue by daonb** [hasadna/Open-Subs#12]
We need a facebook app so we can access the open graph API.  It allows us to define, get and post user's objects and actions.

**Comment by daonb** [comment]
oops, I did it and made @OriHoch an admin too - https://developers.facebook.com/apps/320662434793847

**Comment by OriHoch** [comment]
https://github.com/hasadna/Open-Knesset/pull/309
https://github.com/hasadna/Open-Subs/pull/15

**Comment by OriHoch** [comment]
there is a deployment document in our docs - details what to do

for now, each developer can create his own test app
