### ISSUE TITLE
when selecting some candidates - the image doesn't change

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Subs#47]
![uploads/153dbc21-76b5-47d4-ab53-ea98f8a98283/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F153dbc21-76b5-47d4-ab53-ea98f8a98283%2Fblob)

**Comment by daonb** [comment]
It's because their name is not the main we have in open knesset and they don't have an image....
